#!/usr/bin/env python3
import logging
import os
import sys
import typing

from dotenv import load_dotenv
from pathlib import Path

sys.path.insert(1, os.path.dirname(os.path.dirname(__file__)))
import erato

# load our environment
load_dotenv()
TOKEN = os.getenv('DISCORD_TOKEN')
LEVEL = getattr(logging, os.getenv('LOG_LEVEL', 'INFO'))

#configure logging
logging.basicConfig(encoding='utf-8', level=LEVEL,
        format='%(asctime)s:%(levelname)s:%(name)s: %(message)s')
logger = logging.getLogger(Path(__file__).resolve().name)

#configure our bot
bot = erato.Bot(command_prefix="!")

@bot.command()
async def roll(ctx, ndice: typing.Optional[int] = 2, nsides: typing.Optional[int] = 6):
    msg = ctx.roll(ndice, nsides)
    await ctx.send(msg)

# run
bot.run(TOKEN)
