#!/usr/bin/env python3
import discord
import logging
import os
import random
import typing

from discord.ext import commands
from dotenv import load_dotenv
from functools import reduce
from pathlib import Path

# load our environment
load_dotenv()
TOKEN = os.getenv('DISCORD_TOKEN')
LEVEL = getattr(logging, os.getenv('LOG_LEVEL', 'INFO'))

#configure logging
logging.basicConfig(encoding='utf-8', level=LEVEL,
        format='%(asctime)s:%(levelname)s:%(name)s: %(message)s')
logger = logging.getLogger(Path(__file__).resolve().name)

#configure our bot
bot = commands.Bot(command_prefix="!")

@bot.command()
async def roll(ctx, ndice: typing.Optional[int] = 2, nsides: typing.Optional[int] = 6):
    dice = [random.choice(range(1, nsides + 1)) for _ in range(ndice)]
    sum = reduce(lambda a, b: a + b, dice)
    await ctx.send(' + '.join(map(lambda d: str(d), dice)) + ' = ' + str(sum))

# run
bot.run(TOKEN)
